#!/bin/bash

./dineroIV -l1-usize 8 -l1-ubsize 4 -l1-uassoc 2 -informat d < test.din > lru.out
./dineroIV -l1-usize 8 -l1-ubsize 4 -l1-uassoc 2 -l1-urepl m -informat d < test.din > mru.out




echo Simulation Done!
